steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'us-west1-docker.pkg.dev/qwiklabs-gcp-04-56c502006c80/my-repository/hello-cloudbuild:v1.0'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'us-west1-docker.pkg.dev/qwiklabs-gcp-04-56c502006c80/my-repository/hello-cloudbuild:v1.0'
options:
  logging: CLOUD_LOGGING_ONLY
# force clear cache v2
